### ISSUE TITLE
adding parser to beautifulsoup

### ISSUE THREAD

**Issue by nicesoul** [CorentinChanet/challenge-collecting-data#8]
https://github.com/CorentinChanet/challenge-collecting-data/blob/1f9d6d964fff3ad88bc3e5cbeb460a01d424417a/utils/fetching.py#L63

I am using it like 
item_soup = BeautifulSoup(r.content, **'html5lib'**)
could we add it?

**Comment by CorentinChanet** [comment]
We could, but the problem is that people will have different parsers. For instance, html5lib was not in my python environment (and even when I tried to install and use it, it failed for an unknown reason). Not passing any argument does raise a warning message in the console, but it allows BeautifulSoup to select any available parser. There's probably a cleaner way to deal with this, but I admit I didn't really take the time to focus on that :-/

**Comment by nicesoul** [comment]
Wait, it's working now without an explicit parser - it was not fetching before. I just got a message: 

> GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
Where does it come? From Beautifulsoup itself?

**Comment by CorentinChanet** [comment]
Yes, it's from BeautifulSoup - a very considerate library! :-))
